language: c
sudo: required
compiler: gcc-7
dist: trusty
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse" -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libglib2.0-dev libjson-glib-dev
addons:
  apt:
    packages:
      - autoconf
      - automake
      - libglib2.0-dev
      - libjson-glib-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - squashfs-tools
      - dosfstools
      - lcov
      - slirp
      - python-sphinx
      - dbus-x11
      - gcc-7
      - user-mode-linux
      - grub-common
    sources: &sources
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse'
  coverity_scan:
    project:
      name: "jluebbe/rauc"
      description: "Robust Auto-Update Controller"
    notification_email: jlu@pengutronix.de
    build_command_prepend: "cov-configure --comptype gcc --compiler gcc-7 --template && ./autogen.sh && ./configure"
    build_command: "make -j2"
    branch_pattern: master
before_script:
  - ./build-uncrustify.sh
script:
  - ./autogen.sh
  - ./configure --enable-code-coverage
  - make clean
  - make -j2
  - make doc SPHINXOPTS=-W
  - make check TESTS= && sudo ./uml-test
  - make distcheck
after_success:
  - coveralls --build-root '.' --exclude test --exclude rauc-installer-generated.c
  - ./uncrustify.sh && git diff --exit-code
after_failure:
  - cat test/*.log
  - cat test-suite.log
  - ./uncrustify.sh && git diff --exit-code
